AppLibros/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView



app_name = "AppLibros"


urlpatterns = [
    path("index/", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("libro/buscar", views.buscar_libro, name="buscar_libro"),
    path("libro/buscar/resultados", views.buscar_libro_accion),
    path("autor/buscar", views.buscar_autor, name="buscar_autor"),
    path("autor/buscar/resultados", views.buscar_autor_accion),
    path("socio/buscar", views.buscar_socio, name="buscar_socio"),
    path("socio/buscar/resultados", views.buscar_socio_accion),
    # path("libro/agregar/", views.agregar_libro, name="agregar_libro"),
    # path("libros/", views.listar_libros, name="libros"),
    # path("autor/agregar/", views.agregar_autor, name="agregar_autor"),
    # path("autores/", views.listar_autores, name="autores"),
    # path("socio/agregar", views.agregar_socio, name="agregar_socio"),
    # path("socios/", views.listar_socios, name="socios"),
    # URLs de CBV:
    # se requiere que la variable que se le pase al path o la ruta se llame PK, que es la representacion de Primary Key
    path("libros/lista", views.LibroListView.as_view(), name="ListaLibros"),
    path("libros/nuevo", views.LibroCreateView.as_view(), name="NuevoLibro"),
    path("libros/<pk>", views.LibroDetailView.as_view(), name="DetalleLibro"),
    path("libros/<pk>/editar", views.LibroUpdateView.as_view(), name="EditarLibro"),
    path("libros/<pk>/borrar", views.LibroDeleteView.as_view(), name="BorrarLibro"),
    path("socios/lista", views.SocioListView.as_view(), name="ListaSocios"),
    path("socios/nuevo", views.SocioCreateView.as_view(), name="NuevoSocio"),
    path("socios/<pk>", views.SocioDetailView.as_view(), name="DetalleSocio"),
    path("socios/<pk>/editar", views.SocioUpdateView.as_view(), name="EditarSocio"),
    path("socios/<pk>/borrar", views.SocioDeleteView.as_view(), name="BorrarSocio"),
    path("autores/lista", views.AutorListView.as_view(), name="ListaAutores"),
    path("autores/nuevo", views.AutorCreateView.as_view(), name="NuevoAutor"),
    path("autores/<pk>", views.AutorDetailView.as_view(), name="DetalleAutor"),
    path("autores/<pk>/editar", views.AutorUpdateView.as_view(), name="EditarAutor"),
    path("autores/<pk>/borrar", views.AutorDeleteView.as_view(), name="BorrarAutor"),
    # Login
    path("login", views.login_request, name="Login"),
    path("registro", views.registro, name="Registro"),
    path("logout", LogoutView.as_view(template_name="logout.html"), name="Logout"),
    path("editarPerfil", views.editarPerfil, name="EditarPerfil"),
    path("cambiarContrasena", views.CambiarPass.as_view(), name="CambiarContrasena"),
]

ProyectoLibreria/urls.py
from django.contrib import admin
from django.urls import path, include

# para las imagenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("AppLibros/", include("AppLibros.urls")),
    path("AppPrestamos/", include("AppPrestamos.urls")),
    # path("AppLibros/libros", views.libros),
    # path("AppLibros/main", views.main_de_libros),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppLibros/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Libro(models.Model):
    titulo = models.CharField(max_length=80)
    autor = models.CharField(max_length=120)
    cantidad_paginas = models.IntegerField()

    def __str__(self) -> str:
        return f"titulo: {self.titulo} - autor: {self.autor} - cantidad de paginas: {self.cantidad_paginas}"


class Autor(models.Model):
    nombre = models.CharField(max_length=80)
    apellido = models.CharField(max_length=80)
    fecha_nacimiento = models.DateField()

    def __str__(self) -> str:
        return f"Nombre: {self.nombre} - Apellido: {self.apellido} - fecha de nacimiento: {self.fecha_nacimiento}"


class Socio(models.Model):
    nombre = models.CharField(max_length=80)
    apellido = models.CharField(max_length=120)
    fecha_nacimiento = models.DateField()
    # ficha_id = models.IntegerField()
    email = models.EmailField(default="a@a.com")

    def __str__(self) -> str:
        return f"Nombre: {self.nombre} - Apellido: {self.apellido} - fecha de nacimiento: {self.fecha_nacimiento} - ficha: {self.ficha_id}"


class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.imagen}"

AppLibros/forms.py
from django import forms
from .models import Libro, Autor, Socio
from django.contrib.auth.forms import UserCreationForm, UserModel, UserChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class LibroForm(forms.ModelForm):
    class Meta:
        model = Libro
        fields = ["titulo", "autor", "cantidad_paginas"]


class DateInput(forms.DateInput):
    input_type = "date"


class AutorForm(forms.ModelForm):
    class Meta:
        model = Autor
        fields = ["nombre", "apellido", "fecha_nacimiento"]
        widgets = {
            "fecha_nacimiento": DateInput(),
        }


class SocioForm(forms.ModelForm):
    class Meta:
        model = Socio
        fields = ["nombre", "apellido", "fecha_nacimiento", "email"]
        widgets = {
            "fecha_nacimiento": DateInput(),
        }


class UserCreationFormCustom(UserCreationForm):
    username = forms.CharField(label="Usuario", min_length=5, max_length=15)
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
        model = UserModel
        fields = ["username", "email", "password1", "password2"]
        # Para sacar los mensajes de ayuda
        help_texts = {k: "" for k in fields}


class UserEditForm(UserChangeForm):
    password = None
    email = forms.EmailField(label="Ingrese su email: ")
    last_name = forms.CharField(label="Apellido")
    first_name = forms.CharField(label="Nombre")

    class Meta:
        model = User
        fields = ["email", "last_name", "first_name"]

AppLibros/views.py
from django.http import HttpResponse
from django.template import Template, Context, loader
from . import models
from django.shortcuts import redirect, render
from .forms import LibroForm, AutorForm, SocioForm, UserCreationFormCustom, UserEditForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.views import PasswordChangeView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# from django.contrib.auth.models import User


@login_required
def buscar_autor(request):
    plantilla = loader.get_template("buscarAutor.html")
    return HttpResponse(plantilla.render())


@login_required
def buscar_autor_accion(request):
    if request.method == "GET":
        autor_buscado = request.GET["autorBuscado"]
        autores = models.Autor.objects.filter(nombre__icontains=autor_buscado)
        return render(
            request,
            "buscarAutor.html",
            {"autores": autores, "autor_buscado": autor_buscado},
        )
    else:
        mensaje = "No se encontró ningun autor"
        plantilla = loader.get_template("buscarAutor.html")
        return HttpResponse(plantilla.render({"mensaje": mensaje}))


@login_required
def buscar_libro(request):
    plantilla = loader.get_template("buscarLibro.html")
    return HttpResponse(plantilla.render())


@login_required
def buscar_libro_accion(request):
    if request.method == "GET":
        titulo_buscado = request.GET["tituloBuscado"]
        libros = models.Libro.objects.filter(titulo__icontains=titulo_buscado)
        return render(
            request,
            "buscarLibro.html",
            {"libros": libros, "titulo_buscado": titulo_buscado},
        )
    else:
        mensaje = "No se encontró ningun libro con ese titulo"
        plantilla = loader.get_template("buscarLibro.html")
        return HttpResponse(plantilla.render({"mensaje": mensaje}))


@login_required
def buscar_socio(request):
    plantilla = loader.get_template("buscarSocio.html")
    return HttpResponse(plantilla.render())


@login_required
def buscar_socio_accion(request):
    if request.method == "GET":
        socio_buscado = request.GET["socioBuscado"]
        socios = models.Socio.objects.filter(nombre__icontains=socio_buscado)
        return render(
            request,
            "buscarSocio.html",
            {"socios": socios, "socio_buscado": socio_buscado},
        )
    else:
        mensaje = "No se encontró ningun socio con ese nombre"
        plantilla = loader.get_template("buscarSocio.html")
        return HttpResponse(plantilla.render({"mensaje": mensaje}))


# def listar_autores(request):
#     autores = models.Autor.objects.all()
#     dic_autores = {"autores": autores}
#     plantilla = loader.get_template("listadoAutores.html")
#     return HttpResponse(plantilla.render(dic_autores))


# def listar_libros(request):
#     libros = models.Libro.objects.all()
#     dic_libros = {"libros": libros}
#     plantilla = loader.get_template("listadoLibros.html")
#     return HttpResponse(plantilla.render(dic_libros))


# def listar_socios(request):
#     socios = models.Socio.objects.all()
#     dic_socios = {"socios": socios}
#     plantilla = loader.get_template("listadoSocios.html")
#     return HttpResponse(plantilla.render(dic_socios))


def index(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")


def contact(request):
    return render(request, "contact.html")


# def agregar_libro(request):
#     if request.method == "POST":
#         form = LibroForm(request.POST)
#         if form.is_valid():
#             libro = form.save()
#             return redirect("AppLibros:index")
#     else:
#         form = LibroForm()
#     return render(request, "libro_form.html", {"form": form})


# def agregar_socio(request):
#     if request.method == "POST":
#         form = SocioForm(request.POST)
#         if form.is_valid():
#             socio = form.save()
#             return redirect("AppLibros:index")
#     else:
#         form = SocioForm()
#     return render(request, "socio_form.html", {"form": form})


# def agregar_autor(request):
#     if request.method == "POST":
#         form = AutorForm(request.POST)
#         if form.is_valid():
#             autor = form.save()
#             return redirect("AppLibros:index")
#     else:
#         form = AutorForm()
#     return render(request, "autor_form.html", {"form": form})


class LibroListView(LoginRequiredMixin, ListView):
    model = models.Libro
    context_object_name = "libros"
    template_name = "CBV_libroLista.html"


class LibroDetailView(LoginRequiredMixin, DetailView):
    model = models.Libro
    template_name = "CBV_libroDetalle.html"


class LibroCreateView(LoginRequiredMixin, CreateView):
    model = models.Libro
    template_name = "CBV_libroCrear.html"
    success_url = reverse_lazy("AppLibros:ListaLibros")
    fields = ["titulo", "autor", "cantidad_paginas"]


class LibroUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Libro
    template_name = "CBV_libroEditar.html"
    success_url = reverse_lazy("AppLibros:ListaLibros")
    fields = ["titulo", "autor", "cantidad_paginas"]


class LibroDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Libro
    template_name = "CBV_libroBorrar.html"
    success_url = reverse_lazy("AppLibros:ListaLibros")
    fields = ["titulo", "autor", "cantidad_paginas"]


class SocioListView(LoginRequiredMixin, ListView):
    model = models.Socio
    context_object_name = "socios"
    template_name = "CBV_socioLista.html"


class SocioDetailView(LoginRequiredMixin, DetailView):
    model = models.Socio
    template_name = "CBV_socioDetalle.html"


class SocioCreateView(LoginRequiredMixin, CreateView):
    model = models.Socio
    form_class = SocioForm
    template_name = "CBV_socioCrear.html"
    success_url = reverse_lazy("AppLibros:ListaSocios")
    # fields = ["nombre", "apellido", "fecha_nacimiento", "ficha_id"]


class SocioUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Socio
    template_name = "CBV_socioEditar.html"
    success_url = reverse_lazy("AppLibros:ListaSocios")
    fields = ["nombre", "apellido", "fecha_nacimiento", "email"]


class SocioDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Socio
    template_name = "CBV_socioBorrar.html"
    success_url = reverse_lazy("AppLibros:ListaSocios")
    fields = ["nombre", "apellido", "fecha_nacimiento", "email"]


class AutorListView(LoginRequiredMixin, ListView):
    model = models.Autor
    context_object_name = "autores"
    template_name = "CBV_autorLista.html"


class AutorDetailView(LoginRequiredMixin, DetailView):
    model = models.Autor
    template_name = "CBV_autorDetalle.html"


class AutorCreateView(LoginRequiredMixin, CreateView):
    model = models.Autor
    form_class = AutorForm
    template_name = "CBV_autorCrear.html"
    success_url = reverse_lazy("AppLibros:ListaAutores")
    # fields = ["nombre", "apellido", "fecha_nacimiento"]


class AutorUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Autor
    template_name = "CBV_autorEditar.html"
    success_url = reverse_lazy("AppLibros:ListaAutores")
    fields = ["nombre", "apellido", "fecha_nacimiento"]


class AutorDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Autor
    template_name = "CBV_autorBorrar.html"
    success_url = reverse_lazy("AppLibros:ListaAutores")
    fields = ["nombre", "apellido", "fecha_nacimiento"]


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contrasena = form.cleaned_data.get("password")

            user = authenticate(username=usuario, password=contrasena)

            login(request, user)
            return render(request, "index.html")
        else:
            return render(
                request, "index.html", {"mensaje": f"Usuario o contraseña incorrectos."}
            )
    else:
        form = AuthenticationForm()
    return render(request, "login.html", {"form": form})


def registro(request):
    if request.method == "POST":
        form = UserCreationFormCustom(request.POST)
        if form.is_valid():
            form.save()
            new_user_username = form.cleaned_data.get("username")
            messages.success = (request, f"Usuario {new_user_username}creado")
            form = UserCreationFormCustom()
    else:
        form = UserCreationFormCustom()

    context = {"form": form}
    return render(request, "registro.html", context)


@login_required
def user_logout(request):
    logout(request)
    return redirect("AppLibros:index")


def editarPerfil(request):
    usuario = request.user
    if request.method == "POST":
        miFormulario = UserEditForm(request.POST, instance=request.user)

        if miFormulario.is_valid():
            miFormulario.save()
            return render(request, "index.html")
    else:
        miFormulario = UserEditForm(instance=request.user)
    return render(request, "editarPerfil.html", {"miFormulario": miFormulario})


class CambiarPass(LoginRequiredMixin, PasswordChangeView):
    template_name = "cambiarPass.html"
    success_url = reverse_lazy("AppLibros:EditarPerfil")

AppLibros/templates/CBV_libroCrear.html
{% extends 'padre.html'%}

{% load static %}

{% block contenido %}

<h1> Crear Libro</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Crear">
</form>
<br />
<p>
    <a href={% url "AppLibros:ListaLibros" %}>Regresar</a>
</p>


{% endblock contenido %}

AppLibros/templates/indexPrestamos.html
{% extends 'padre.html'%}

{% load static %}

{% block contenido %}

{% if mensaje %}
<p>{{ mensaje }}</p>
{% endif %}

<h1>Prestamos</h1>


{% endblock contenido %}

AppLibros/templates/padre.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title> Hogwarts Library </title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"
        type="text/css" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'AppLibros/css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" href={% url "AppLibros:index" %}>Inicio</a>
            <a class="navbar-brand" href={% url "AppLibros:ListaLibros" %}>Libros</a>
            <a class="navbar-brand" href={% url "AppLibros:ListaSocios" %}>Socios</a>
            <a class="navbar-brand" href={% url "AppLibros:ListaAutores" %}>Autores</a>
            <a class="btn-primary" href={% url "AppLibros:Login" %}>Login</a>
            <a class="btn btn-primary" href={% url "AppLibros:Registro" %}>Registro</a>
            <a class="btn-primary" href={% url "AppLibros:Logout" %}>Logout</a>
            <!-- <a class="btn btn-primary" href="#!">Sign Up</a> -->
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <h1 class="mb-5">Bienvenidos a la web de la biblioteca de Hogwarts!</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    {% block contenido %}

    {% endblock contenido %}

    <!-- Footer-->
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item"><a href="#!">About</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Contact</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-facebook fs-3"></i></a>
                        </li>
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-twitter fs-3"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!"><i class="bi-instagram fs-3"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static '/AppLibros/js/scripts.js' %}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

</body>

</html>