AppLibros/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView



app_name = "AppLibros"


urlpatterns = [
    path("index/", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("libro/buscar", views.buscar_libro, name="buscar_libro"),
    path("libro/buscar/resultados", views.buscar_libro_accion),
    path("autor/buscar", views.buscar_autor, name="buscar_autor"),
    path("autor/buscar/resultados", views.buscar_autor_accion),
    path("socio/buscar", views.buscar_socio, name="buscar_socio"),
    path("socio/buscar/resultados", views.buscar_socio_accion),
    # path("libro/agregar/", views.agregar_libro, name="agregar_libro"),
    # path("libros/", views.listar_libros, name="libros"),
    # path("autor/agregar/", views.agregar_autor, name="agregar_autor"),
    # path("autores/", views.listar_autores, name="autores"),
    # path("socio/agregar", views.agregar_socio, name="agregar_socio"),
    # path("socios/", views.listar_socios, name="socios"),
    # URLs de CBV:
    # se requiere que la variable que se le pase al path o la ruta se llame PK, que es la representacion de Primary Key
    path("libros/lista", views.LibroListView.as_view(), name="ListaLibros"),
    path("libros/nuevo", views.LibroCreateView.as_view(), name="NuevoLibro"),
    path("libros/<pk>", views.LibroDetailView.as_view(), name="DetalleLibro"),
    path("libros/<pk>/editar", views.LibroUpdateView.as_view(), name="EditarLibro"),
    path("libros/<pk>/borrar", views.LibroDeleteView.as_view(), name="BorrarLibro"),
    path("socios/lista", views.SocioListView.as_view(), name="ListaSocios"),
    path("socios/nuevo", views.SocioCreateView.as_view(), name="NuevoSocio"),
    path("socios/<pk>", views.SocioDetailView.as_view(), name="DetalleSocio"),
    path("socios/<pk>/editar", views.SocioUpdateView.as_view(), name="EditarSocio"),
    path("socios/<pk>/borrar", views.SocioDeleteView.as_view(), name="BorrarSocio"),
    path("autores/lista", views.AutorListView.as_view(), name="ListaAutores"),
    path("autores/nuevo", views.AutorCreateView.as_view(), name="NuevoAutor"),
    path("autores/<pk>", views.AutorDetailView.as_view(), name="DetalleAutor"),
    path("autores/<pk>/editar", views.AutorUpdateView.as_view(), name="EditarAutor"),
    path("autores/<pk>/borrar", views.AutorDeleteView.as_view(), name="BorrarAutor"),
    # Login
    path("login", views.login_request, name="Login"),
    path("registro", views.registro, name="Registro"),
    path("logout", LogoutView.as_view(template_name="logout.html"), name="Logout"),
    path("editarPerfil", views.editarPerfil, name="EditarPerfil"),
    path("cambiarContrasena", views.CambiarPass.as_view(), name="CambiarContrasena"),
]

AppPrestamos/urls.py
from django.urls import path
from . import views

app_name = "AppPrestamos"


urlpatterns = [
    path("index/", views.index, name="index"),
    path("prestamos/lista", views.PrestamoListView.as_view(), name="ListaPrestamos"),
    path(
        "prestamo/<pk>/editar",
        views.PrestamoUpdateView.as_view(),
        name="EditarPrestamo",
    ),
    # path("login", views.login_request, name="Login"),
    # path("registro", views.registro, name="Registro"),
    # path("logout", LogoutView.as_view(template_name="logout.html"), name="Logout"),
]

ProyectoLibreria/urls.py
from django.contrib import admin
from django.urls import path, include

# para las imagenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("AppLibros/", include("AppLibros.urls")),
    path("AppPrestamos/", include("AppPrestamos.urls")),
    # path("AppLibros/libros", views.libros),
    # path("AppLibros/main", views.main_de_libros),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppPrestamos/models.py
from django.db import models

# Create your models here.


class Prestamo(models.Model):
    socio_id = models.IntegerField()
    libro_id = models.IntegerField()
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    devuelto = models.BooleanField()

AppPrestamos/forms.py
from django import forms
from .models import Prestamo


class DateInput(forms.DateInput):
    input_type = "date"


class PrestamoForm(forms.ModelForm):
    class Meta:
        model = Prestamo
        fields = ["socio_id", "libro_id", "fecha_inicio", "fecha_fin", "devuelto"]
        widgets = {
            "fecha_inicio": DateInput(),
            "fecha_fin": DateInput(),
        }

AppPrestamos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.decorators import login_required
from .forms import PrestamoForm
from django.contrib import messages
from AppLibros.models import Socio, Libro
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy


@login_required
def index(request):
    if request.method == "GET":
        # messages.info(request, "Ingrese al menos 3 letras en su busqueda")
        lista_nombres = buscar_socios()
        lista_libros = buscar_libros()
        form = PrestamoForm()
        return render(
            request,
            "indexPrest.html",
            {
                "form": form,
                "lista_nombres": lista_nombres,
                "lista_libros": lista_libros,
            },
        )

    if request.method == "POST":
        form = PrestamoForm(request.POST)
        if form.is_valid():
            form.save()
            # messages.success = (request, f"Prestamo registrado!")
            return redirect("AppPrestamos:index")

    form = PrestamoForm()
    return render(request, "indexPrest.html", {"form": form})


def buscar_socios():
    lista_socios = Socio.objects.all()
    return lista_socios


def buscar_libros():
    lista_libros = Libro.objects.all()
    return lista_libros


class PrestamoListView(LoginRequiredMixin, ListView):
    model = models.Prestamo
    context_object_name = "prestamos"
    template_name = "CBV_prestamoLista.html"


class PrestamoUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Prestamo
    template_name = "CBV_prestamoEditar.html"
    success_url = reverse_lazy("AppPrestamos:index")
    fields = ["socio_id", "libro_id", "fecha_inicio", "fecha_fin", "devuelto"]

AppPrestamos/templates/AppPrestamos/CBV_prestamoEditar.html
{% extends 'padre.html'%}

{% load static %}

{% block contenido %}

<h1> Editar prestamo </h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Editar">
</form>

<br />
<p>
    <a href={% url "AppPrestamos:ListaPrestamos" %}>Regresar</a>
</p>

{% endblock contenido %}

AppPrestamos/templates/AppPrestamos/CBV_prestamoLista.html
{% extends 'padre.html'%}

{% load static %}

{% block contenido %}

<h1> Listado de prestamos </h1>

<table id="sociosTable">
    <tr>
        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
            <b>Id de socio</b>
        </td>
        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
            <b>Id de libro</b>
        </td>
        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
            <b>Devuelto</b>
        </td>
        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
            <span>&nbsp</span>
        </td>
    </tr>
    <tbody>
        {% for p in prestamos %}
        <tr>
            <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">{{ p.socio_id }}</td>
            <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">{{ p.libro_id }} </td>
            <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
                {% if p.devuelto %}
                <span>Sí </span>
                {% else %}
                <span>No </span>
                {% endif %}
            </td>
            <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;"><a href={% url "AppPrestamos:EditarPrestamo" p.pk %}>Editar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<br />
<p>
    <a href={% url "AppPrestamos:index" %}>Regresar</a>
</p>

{% endblock contenido %}

AppPrestamos/templates/AppPrestamos/indexPrest.html
{% extends 'AppLibros/padre.html'%}

{% load static %}

{% block contenido %}

<h3>Registrar prestamo</h3>

{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h4>
    <a href={% url "AppPrestamos:ListaPrestamos" %}>Ver prestamos</a>
</h4>

<table id="general">
    <tr>
        <td>
            <label for="sociosTable">
                <h5>Socios</h5>
            </label>
            <table id="sociosTable">
                <tr>
                    <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
                        <b>id</b>
                    </td>
                    <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
                        <b>Nombre</b>
                    </td>
                    <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
                        <b>Apellido</b>
                    </td>
                </tr>
                <tbody>
                    {% for socio in lista_nombres %}
                    <tr>
                        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">{{ socio.pk }}</td>
                        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">{{ socio.nombre }}
                        </td>
                        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">{{ socio.apellido }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </td>
        <td>
            <label for="librosTable">
                <h5>Libros</h5>
            </label>
            <table id="librosTable">
                <tr>
                    <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
                        <b>id</b>
                    </td>
                    <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
                        <b>Titulo</b>
                    </td>
                    <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">
                        <b>Autor</b>
                    </td>
                </tr>
                <tbody>
                    {% for libro in lista_libros %}
                    <tr>
                        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">{{ libro.pk }}</td>
                        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">{{ libro.titulo }}
                        </td>
                        <td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">{{ libro.autor }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </td>
    </tr>
</table>


<hr>

<div>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Enviar</button>
    </form>
</div>


{% endblock contenido %}